// ═══════════════════════════════════════════════════════════════════════════════
// GOOGLE CREDENTIALS CONFIGURATION TEMPLATE
// ═══════════════════════════════════════════════════════════════════════════════
//
// ⚠️  DO NOT EDIT THIS FILE
//
// This file is a TEMPLATE showing the expected credential structure.
// Your ACTUAL credentials should NEVER be committed to git.
//
// Em Dash stores every document in Google Drive — there is no other storage
// backend — so a working Google OAuth client is required for the app to be
// useful at all.
//
// ─────────────────────────────────────────────────────────────────────────────
// FOR LOCAL DEVELOPMENT
// ─────────────────────────────────────────────────────────────────────────────
//
// 1. Copy this file: cp config.example.js config.js
// 2. Edit config.js and replace the PLACEHOLDER values with your actual
//    credentials from Google Cloud Console
// 3. The config.js file is in .gitignore and will never be committed
//
// ─────────────────────────────────────────────────────────────────────────────
// FOR PRODUCTION DEPLOYMENT (Vercel)
// ─────────────────────────────────────────────────────────────────────────────
//
// Credentials are automatically injected at build time by build-config.js,
// which reads them from Vercel Environment Variables. The deployed application
// will have real credentials in window.APP_CONFIG, but they are never visible in:
// - Git history
// - Build logs (env vars are masked)
// - Source code repository
//
// ═══════════════════════════════════════════════════════════════════════════════

window.APP_CONFIG = {
  // OAuth 2.0 Client ID - obtained from Google Cloud Console
  // Format: NUMBERS-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.apps.googleusercontent.com
  // ⚠️  NEVER commit the real value to git
  GOOGLE_CLIENT_ID: 'PLACEHOLDER_CLIENT_ID.apps.googleusercontent.com',

  // Google API Key - obtained from Google Cloud Console
  // Format: AIzaSyXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  // ⚠️  NEVER commit the real value to git
  // Restrictions applied:
  // - HTTP referrer: https://yourdomain.com/* and http://localhost:8000/*
  // - API: Google Drive API only
  GOOGLE_API_KEY: 'PLACEHOLDER_API_KEY',

};

// ─────────────────────────────────────────────────────────────────────────────
// Quick Start
// ─────────────────────────────────────────────────────────────────────────────
// 1. cp config.example.js config.js
// 2. Visit: https://console.cloud.google.com/apis/credentials
// 3. Copy your OAuth Client ID and API Key
// 4. Paste them into config.js (replace PLACEHOLDER_*)
// 5. Start the server: python3 -m http.server 8000
// 6. Open: http://localhost:8000
// ─────────────────────────────────────────────────────────────────────────────
